version: '3.5'

services:
  # stellar_ms_web:
  #   build: .
  #   container_name: stellar_ms_web
  #   command: uvicorn application.main:app
  #   env_file:
  #     - ./.env
  #   expose:
  #     - 8000
  #   restart: always

  stellar_ms_redis:
    container_name: stellar_ms_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:6-alpine
    volumes:
      - ./redis/data:/redis/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/log:/root/redis/log
    logging:
      options:
        max-size: 10m
    expose:
      - 6379
    restart: unless-stopped

  stellar_ms_celery:
    build: .
    container_name: stellar_ms_celery
    command: bash -c "celery -A conf worker -l INFO"
    env_file:
      - ./.env
    depends_on:
      # - stellar_ms_web
      - stellar_ms_redis
    restart: always

  stellar_ms_celery-beat:
    build: .
    container_name: stellar_ms_celery-beat
    command: celery -A conf beat -l INFO
    env_file:
      - ./.env
    depends_on:
      # - stellar_ms_web
      - stellar_ms_redis
    restart: always

  # dashboard:
  #     build: .
  #     command: celery -A conf flower --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} --port=5555 --url_prefix=flower
  #     ports:
  #       - 5555:5555
  #     environment:
  #       CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  #       CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
  #     env_file:
  #       - ./.env
  #     depends_on:
  #       # - stellar_ms_web
  #       - stellar_ms_redis
  #       - stellar_ms_celery
