version: '3.6'

services:
  web:
    build: .
    container_name: web
    command: uvicorn application.main:app
    env_file:
      - ./.env
    expose:
      - 8000
    restart: always

  redis:
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:6-alpine
    volumes:
      - ./redis/data:/redis/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/log:/root/redis/log
    logging:
      options:
        max-size: 10m
    expose:
      - 6379
    restart: unless-stopped

  celery:
    build: .
    container_name: celery
    command: bash -c "celery -A conf worker --concurrency 4 -l INFO -n worker1"
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
    restart: always

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A conf beat -l INFO
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
    restart: always

  dashboard:
      build: .
      command: celery -A conf flower --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} --port=5555 --url_prefix=flower
      ports:
        - 5555:5555
      environment:
        CELERY_BROKER_URL: ${CELERY_BROKER_URL}
        CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      env_file:
        - ./.env
      depends_on:
        - web
        - redis
        - celery
