[tool.poetry]
name = "stellar-microservice"
version = "0.1.0"
description = ""
authors = ["Sergey Danilov <sergej.d@itfox-web.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.1"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
stellar-sdk = "^7.0.1"
celery = "^5.2.6"
redis = "^4.2.2"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
